// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "arduino_secrets.h"
const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onTankCapacityChange();

CloudVolume tank_Capacity;

void initProperties(){

  ArduinoCloud.addProperty(tank_Capacity, READWRITE, ON_CHANGE, onTankCapacityChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);

